name: 'Build artifacts'

on:
  workflow_call:
    inputs:
      tag:
        required: false
        type: string

jobs:
#  build-windows:
#    name: Windows
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Build all
#        shell: bash
#        run: |
#          ./build_all
#      - name: Create artifact
#        shell: bash
#        run: |
#          7z a Install/Sandbox.7z Install/Sandbox
#      - uses: actions/upload-artifact@v4
#        with:
#          name: Artifact-Windows
#          path: Install/Sandbox.7z
#          if-no-files-found: error

  build-linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Build all
        run: |
          ./build_all
      - name: Create release version file
        if: ${{ inputs.tag != '' }}
        run: |
          python3 Buildsystem/CreateReleaseVersionFile.py ${{  inputs.tag }} Install/Sandbox
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts-Linux
          path: Install/Sandbox
          if-no-files-found: error

#  build-macos:
#    name: MacOS
#    runs-on: macos-11
#    steps:
#      - uses: actions/checkout@v4
#      - name: Build all
#        shell: bash
#        run: |
#          ./build_all
#      - name: Create artifact
#        shell: bash
#        run: |
#          tar zcvf Install/Sandbox.tgz Install/Sandbox
#      - uses: actions/upload-artifact@v4
#        with:
#          name: Artifact-MacOS
#          path: Install/Sandbox.tgz
#          if-no-files-found: error