name: 'Create release'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      tag: ${{  github.ref_name }}
  Release:
    name: Release
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: create_release
        uses: actions/create-release@v1
        id: create_release
        with:
          prerelease: true
          release_name: ${{  github.ref_name }}
          tag_name: ${{  github.ref_name }}