name: 'Create release'

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  Build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
      tag: ${{  github.ref_name }}
  Release:
    name: Release
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/download-artifact@v4
      - name: display
        run: ls -la
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --prerelease \
              --verify-tag