name: 'Create release'

on:
  push:
    tags:
      - '*'

jobs:
  build-windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build all
        shell: bash
        run: |
          ./build_all
      - name: Create artifact
        shell: bash
        run: |
          7z a Install/Sandbox.7z Install/Sandbox
      - uses: actions/upload-artifact@v4
        with:
          name: ArtifactW
          path: Install/Sandbox.7z
  build-linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Build all
        shell: bash
        run: |
          ./build_all
      - name: Create artifact
        shell: bash
        run: |
          tar zcvf Install/Sandbox.tgz Install/Sandbox
      - uses: actions/upload-artifact@v4
        with:
          name: ArtifactL
          path: Install/Sandbox.tgz
  build-macos:
    name: MacOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - name: Build all
        shell: bash
        run: |
          ./build_all
      - name: Create artifact
        shell: bash
        run: |
          tar zcvf Install/Sandbox.tgz Install/Sandbox
      - uses: actions/upload-artifact@v4
        with:
          name: ArtifactM
          path: Install/Sandbox.tgz