name: 'Create release'

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    name: Linux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Create artifact
        shell: bash
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}"